version: '3'

services:
  produtosapi:
    image: produtosapi
    ports:
      - "8000:80"
    build: .
    container_name: "produtosapi"     
    links:
      - mongo
    depends_on:
      - mongo
      
   mongo:
        image: mongo:latest
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet  